name: Build artifacts to link to release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: pack mitmproxy with amqp
        run: |
          python -m venv venv
          venv/bin/pip install pyinstaller
          venv/bin/pyinstaller release/specs/standalone.spec
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: pack mitmproxy with amqp
        run: |
          python -m venv venv
          venv/Scripts/pip.exe install pyinstaller
          venv/Scripts/pyinstaller.exe release/specs/standalone.spec
      - name: Archive mitmproxy as artiefact
        uses: actions/upload-artifact@v4
        with:
          name: mitmproxy
          path: dist/mitmweb.exe
